from turtle import *

def draw_corrected_car():
    speed(10)  
    bgcolor("lightblue") 
    penup()
    goto(-100, -50)  
    pendown()
    fillcolor("blue") 
    begin_fill()
    for _ in range(2):
        forward(200)  
        left(90)
        forward(50)  
        left(90)
    end_fill()
    penup()
    goto(-60, 0)  
    pendown()
    fillcolor("darkblue")
    begin_fill()
    for _ in range(2):
        forward(120)  
        left(90)
        forward(30) 
        left(90)
    end_fill()
    penup()
    goto(-50, 10) 
    pendown()
    fillcolor("lightgrey")  
    begin_fill()
    for _ in range(2):
        forward(40)  
        left(90)
        forward(20)  
        left(90)
    end_fill()
    penup()
    goto(10, 10)  
    pendown()
    begin_fill()
    for _ in range(2):
        forward(40) 
        left(90)
        forward(20)  
        left(90)
    end_fill()
    penup()
    goto(-70, -70) 
    pendown()
    fillcolor("black")  
    begin_fill()
    circle(20)  
    end_fill()
    penup()
    goto(50, -70)
    pendown()
    begin_fill()
    circle(20) 
    end_fill()
    penup()
    goto(-100, -50) 
    pendown()
    done()  
draw_corrected_car()